# Site settings
baseurl: "/latin-greek-scientific-terminology"
url: "http://andrewdunning.ca/latin-greek-scientific-terminology"

# Build settings
plugins: plugins
markdown: pandoc
permalink: pretty
pandoc:
  extensions:
    - smart
    - filter=pandoc-citeproc
    - 'bibliography=bibliography.json'
    - 'csl=chicago-author-date.csl'
destination: '../public'
    

# Course information
title: "Latin and Greek in Scientific Terminology"
course_meetingtime: "Thurs. 3:00&ndash;6:00 p.m."
course_number: "CLA 201"
course_room: "Instructional Centre 345"
course_semester: "Fall 2014"
instructor_email: andrew.dunning@utoronto.ca
instructor_name: Andrew Dunning
instructor_website: 'http://andrewdunning.ca/'
instructor_office: "North Building 272A"
instructor_officehours: "Thurs. 2:00&ndash;3:00 p.m."
course_description: "An introduction to the derivation and basic meaning of English technical and scientific vocabulary formed from Latin and Greek elements."
